liaison entre entités category et tutorial faite, lorsqu'on clique su…
WildCodeSchool/2023-03-remote-fr-php-la-banque-postale pull request #14
Opened 2023-06-09 14:04 UTC by ninaschadel

…r la catégorie concernée on arrive sur les bons tutos. J'ai aussi modifié les noms des routes qui étaient en anglais et j'ai changé ls noms de certains fichiers pour que tout soit homogene.

2023-06-09 14:05 UTC, AlexisIMichelas approved these changes

2023-06-09 14:41 UTC, jfm-wcs requested changes
qq petites modifications concernant l'affichage des url dans les twig, utilisez la fonction path() 😉

2023-06-09 14:41 UTC, jfm-wcs commented on templates/choix-mail/index.html.twig
> +				<a href="/mail_tutorial" type="button" class="btn btn-secondary mb-4 btn-lg w-100 text-uppercase">Je n'ai pas d'adresse mail</a>
serait mieux avec {{ path() }} plutôt que le nom en dur, non ?

2023-06-09 14:41 UTC, jfm-wcs commented on templates/connexion/index.html.twig
> +								<a href="/categorie" class="btn btn-success">Clique ici pour te connecter</a>
idem path

2023-06-09 14:41 UTC, jfm-wcs commented on templates/home/index.html.twig
> +				<a href="/categorie" type="button" class="btn btn-success m-auto mb-3 btn-lg w-75 text-uppercase">Je veux essayer sans m'enregistrer</a>
idem path

2023-06-09 14:41 UTC, jfm-wcs commented on templates/include/_navbar.html.twig
> +		<a class="nav-link d-flex align-items-center flex-column-reverse text-light" href="/categorie/">
et re idem path ;)

2023-06-09 14:41 UTC, jfm-wcs commented on templates/inscription/index.html.twig
> +		<a href="/categorie" class="btn btn-success rounded-pill m-2">Clique ici pour t'inscrire</a>
ah un dernier idem path :p

2023-06-12 18:43 UTC, jfm-wcs requested changes
qq petites modifications et c'est good

2023-06-12 18:43 UTC, jfm-wcs commented on src/Controller/CategoryController.php
> +    #[Route('/categorie/{categoryTitle}', name: 'category_show')]
tu devrais enlever le `/categorie` de cette route car c'est déjà préfixé sur la classe, non ?

2023-06-12 18:43 UTC, jfm-wcs commented on templates/home/index.html.twig
> +				<a href="{{ path('index_category') }}" type="button" class="btn btn-success m-auto mb-3 btn-lg w-75 text-uppercase">Je veux essayer sans m'enregistrer</a>
idem `type='button"` à retirer

2023-06-13 15:21 UTC, merged