integration du block nav pour une meilleure adaptation des templates …
WildCodeSchool/2023-03-remote-fr-php-la-banque-postale pull request #9
Opened 2023-06-07 12:55 UTC by titouwork

…(avec/sans)

2023-06-07 13:21 UTC, AlexisIMichelas approved these changes

2023-06-08 06:45 UTC, jfm-wcs requested changes
question block, sinon ok

2023-06-08 06:45 UTC, jfm-wcs commented on templates/base.html.twig
> +
avez-vous vraiment besoin de créer un block nav dans votre système de template ? Un simple include devrait suffire non, à moins que vous ne prévoyez d'insérer d'autres barre de navigation depuis les templates enfants ^-^ ?

2023-06-08 08:46 UTC, jfm-wcs approved these changes

2023-06-08 08:46 UTC, merged